language:
  python

services:
  - elasticsearch
  - docker

python:
  - 3.6

sudo: required

env:
  global:
    - K8S_OPS_REPO_BRANCH=master
    - K8S_OPS_REPO_SLUG=datahq/deploy
    - DOCKER_IMAGE=datopian/datahub-auth
    - DEPLOY_YAML_UPDATE_FILE=values.auto-updated.yaml
    - DEPLOY_VALUES_CHART_NAME=auth
    - DEPLOY_VALUES_IMAGE_PROP=image
    - DEPLOY_COMMIT_MESSAGE="automatic update of dhq-datahub-auth"
    - DEPLOY_GIT_EMAIL=dhq-deployer@null.void
    - DEPLOY_GIT_USER=dhq-deployer

script:
  - curl -s https://raw.githubusercontent.com/datahq/deploy/master/apps_travis_script.sh > .travis.sh
  - bash .travis.sh script

after_success:
  - coveralls

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.sh deploy
  on:
    branch: master
